version: "3" # specify docker-compose version

# Define the services/containers to be run
services:
  client:
    build: ./client
    ports:
      - "4200:4200"
  server: # name of the first service
    build: ./server # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
